export const data = {
  location: {
    name: "London",
    region: "City of London, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.11,
    tz_id: "Europe/London",
    localtime_epoch: 1717020504,
    localtime: "2024-05-29 23:08",
  },
  current: {
    last_updated_epoch: 1717020000,
    last_updated: "2024-05-29 23:00",
    temp_c: 16.0,
    temp_f: 60.8,
    is_day: 0,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
      code: 1000,
    },
    wind_mph: 4.3,
    wind_kph: 6.8,
    wind_degree: 300,
    wind_dir: "WNW",
    pressure_mb: 1009.0,
    pressure_in: 29.8,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 68,
    cloud: 0,
    feelslike_c: 16.0,
    feelslike_f: 60.8,
    windchill_c: 11.8,
    windchill_f: 53.2,
    heatindex_c: 12.8,
    heatindex_f: 55.0,
    dewpoint_c: 10.3,
    dewpoint_f: 50.6,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 11.2,
    gust_kph: 18.0,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-05-29",
        date_epoch: 1716940800,
        day: {
          maxtemp_c: 19.3,
          maxtemp_f: 66.7,
          mintemp_c: 11.6,
          mintemp_f: 53.0,
          avgtemp_c: 15.2,
          avgtemp_f: 59.4,
          maxwind_mph: 11.9,
          maxwind_kph: 19.1,
          totalprecip_mm: 1.04,
          totalprecip_in: 0.04,
          totalsnow_cm: 0.0,
          avgvis_km: 9.5,
          avgvis_miles: 5.0,
          avghumidity: 75,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 89,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain nearby",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: "04:51 AM",
          sunset: "09:06 PM",
          moonrise: "01:43 AM",
          moonset: "10:31 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 69,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1716937200,
            time: "2024-05-29 00:00",
            temp_c: 13.2,
            temp_f: 55.8,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 236,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.25,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 11.8,
            feelslike_f: 53.2,
            windchill_c: 11.8,
            windchill_f: 53.2,
            heatindex_c: 13.2,
            heatindex_f: 55.8,
            dewpoint_c: 12.4,
            dewpoint_f: 54.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1716940800,
            time: "2024-05-29 01:00",
            temp_c: 13.1,
            temp_f: 55.6,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 245,
            wind_dir: "WSW",
            pressure_mb: 1008.0,
            pressure_in: 29.78,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 90,
            feelslike_c: 11.7,
            feelslike_f: 53.1,
            windchill_c: 11.7,
            windchill_f: 53.1,
            heatindex_c: 13.1,
            heatindex_f: 55.6,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 1,
            chance_of_rain: 89,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.5,
            uv: 1.0,
          },
          {
            time_epoch: 1716944400,
            time: "2024-05-29 02:00",
            temp_c: 12.3,
            temp_f: 54.2,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 250,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 0.02,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 10.5,
            feelslike_f: 50.8,
            windchill_c: 10.5,
            windchill_f: 50.8,
            heatindex_c: 12.3,
            heatindex_f: 54.2,
            dewpoint_c: 11.5,
            dewpoint_f: 52.8,
            will_it_rain: 1,
            chance_of_rain: 86,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.6,
            gust_kph: 28.3,
            uv: 1.0,
          },
          {
            time_epoch: 1716948000,
            time: "2024-05-29 03:00",
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 250,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.02,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 93,
            cloud: 100,
            feelslike_c: 9.7,
            feelslike_f: 49.4,
            windchill_c: 9.7,
            windchill_f: 49.4,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            dewpoint_c: 10.7,
            dewpoint_f: 51.3,
            will_it_rain: 1,
            chance_of_rain: 73,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.1,
            gust_kph: 29.1,
            uv: 1.0,
          },
          {
            time_epoch: 1716951600,
            time: "2024-05-29 04:00",
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 245,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 93,
            cloud: 100,
            feelslike_c: 9.9,
            feelslike_f: 49.8,
            windchill_c: 9.9,
            windchill_f: 49.8,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            dewpoint_c: 10.7,
            dewpoint_f: 51.2,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.4,
            uv: 1.0,
          },
          {
            time_epoch: 1716955200,
            time: "2024-05-29 05:00",
            temp_c: 11.6,
            temp_f: 53.0,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 243,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.02,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 93,
            cloud: 86,
            feelslike_c: 9.9,
            feelslike_f: 49.7,
            windchill_c: 9.9,
            windchill_f: 49.7,
            heatindex_c: 11.7,
            heatindex_f: 53.0,
            dewpoint_c: 10.6,
            dewpoint_f: 51.1,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.9,
            gust_kph: 23.9,
            uv: 3.0,
          },
          {
            time_epoch: 1716958800,
            time: "2024-05-29 06:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 243,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 92,
            cloud: 67,
            feelslike_c: 10.5,
            feelslike_f: 50.9,
            windchill_c: 10.5,
            windchill_f: 50.9,
            heatindex_c: 12.1,
            heatindex_f: 53.9,
            dewpoint_c: 10.9,
            dewpoint_f: 51.7,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 21.9,
            uv: 3.0,
          },
          {
            time_epoch: 1716962400,
            time: "2024-05-29 07:00",
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 1,
            condition: {
              text: "Overcast ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 87,
            cloud: 97,
            feelslike_c: 11.8,
            feelslike_f: 53.3,
            windchill_c: 11.8,
            windchill_f: 53.3,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            dewpoint_c: 11.1,
            dewpoint_f: 51.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.8,
            gust_kph: 20.6,
            uv: 3.0,
          },
          {
            time_epoch: 1716966000,
            time: "2024-05-29 08:00",
            temp_c: 14.3,
            temp_f: 57.8,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 262,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.81,
            precip_mm: 0.02,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 80,
            cloud: 95,
            feelslike_c: 13.1,
            feelslike_f: 55.6,
            windchill_c: 13.1,
            windchill_f: 55.6,
            heatindex_c: 14.3,
            heatindex_f: 57.8,
            dewpoint_c: 10.9,
            dewpoint_f: 51.7,
            will_it_rain: 1,
            chance_of_rain: 74,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.0,
            gust_kph: 19.3,
            uv: 3.0,
          },
          {
            time_epoch: 1716969600,
            time: "2024-05-29 09:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.05,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 65,
            cloud: 80,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: 10.0,
            dewpoint_f: 50.0,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.8,
            gust_kph: 19.0,
            uv: 4.0,
          },
          {
            time_epoch: 1716973200,
            time: "2024-05-29 10:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.12,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 62,
            cloud: 61,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 10.1,
            dewpoint_f: 50.3,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.1,
            gust_kph: 19.5,
            uv: 4.0,
          },
          {
            time_epoch: 1716976800,
            time: "2024-05-29 11:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.11,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 60,
            cloud: 60,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 10.0,
            dewpoint_f: 49.9,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 4.0,
          },
          {
            time_epoch: 1716980400,
            time: "2024-05-29 12:00",
            temp_c: 18.0,
            temp_f: 64.4,
            is_day: 1,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/263.png",
              code: 1150,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 285,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.32,
            precip_in: 0.01,
            snow_cm: 0.0,
            humidity: 60,
            cloud: 53,
            feelslike_c: 18.0,
            feelslike_f: 64.4,
            windchill_c: 18.0,
            windchill_f: 64.4,
            heatindex_c: 18.0,
            heatindex_f: 64.4,
            dewpoint_c: 10.1,
            dewpoint_f: 50.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 4.0,
          },
          {
            time_epoch: 1716984000,
            time: "2024-05-29 13:00",
            temp_c: 18.3,
            temp_f: 65.0,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.78,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 56,
            cloud: 77,
            feelslike_c: 18.3,
            feelslike_f: 65.0,
            windchill_c: 18.3,
            windchill_f: 65.0,
            heatindex_c: 18.3,
            heatindex_f: 65.0,
            dewpoint_c: 9.5,
            dewpoint_f: 49.1,
            will_it_rain: 0,
            chance_of_rain: 69,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.8,
            gust_kph: 19.0,
            uv: 4.0,
          },
          {
            time_epoch: 1716987600,
            time: "2024-05-29 14:00",
            temp_c: 18.9,
            temp_f: 66.1,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 52,
            cloud: 60,
            feelslike_c: 18.9,
            feelslike_f: 66.1,
            windchill_c: 18.9,
            windchill_f: 66.1,
            heatindex_c: 18.9,
            heatindex_f: 66.1,
            dewpoint_c: 9.0,
            dewpoint_f: 48.1,
            will_it_rain: 1,
            chance_of_rain: 73,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.6,
            uv: 4.0,
          },
          {
            time_epoch: 1716991200,
            time: "2024-05-29 15:00",
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 288,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 52,
            cloud: 45,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            windchill_c: 19.3,
            windchill_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            dewpoint_c: 9.2,
            dewpoint_f: 48.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.1,
            gust_kph: 19.5,
            uv: 5.0,
          },
          {
            time_epoch: 1716994800,
            time: "2024-05-29 16:00",
            temp_c: 18.7,
            temp_f: 65.7,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 289,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.01,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 55,
            cloud: 70,
            feelslike_c: 18.7,
            feelslike_f: 65.7,
            windchill_c: 18.7,
            windchill_f: 65.7,
            heatindex_c: 18.7,
            heatindex_f: 65.7,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 1,
            chance_of_rain: 83,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.6,
            gust_kph: 20.3,
            uv: 4.0,
          },
          {
            time_epoch: 1716998400,
            time: "2024-05-29 17:00",
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 291,
            wind_dir: "WNW",
            pressure_mb: 1007.0,
            pressure_in: 29.75,
            precip_mm: 0.02,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 57,
            cloud: 61,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 1,
            chance_of_rain: 89,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.9,
            gust_kph: 20.7,
            uv: 4.0,
          },
          {
            time_epoch: 1717002000,
            time: "2024-05-29 18:00",
            temp_c: 17.5,
            temp_f: 63.4,
            is_day: 1,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 298,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.75,
            precip_mm: 0.03,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 64,
            cloud: 85,
            feelslike_c: 17.5,
            feelslike_f: 63.4,
            windchill_c: 17.5,
            windchill_f: 63.4,
            heatindex_c: 17.5,
            heatindex_f: 63.4,
            dewpoint_c: 10.7,
            dewpoint_f: 51.2,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.7,
            gust_kph: 20.4,
            uv: 4.0,
          },
          {
            time_epoch: 1717005600,
            time: "2024-05-29 19:00",
            temp_c: 16.1,
            temp_f: 61.0,
            is_day: 1,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 289,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 71,
            cloud: 26,
            feelslike_c: 16.1,
            feelslike_f: 61.0,
            windchill_c: 16.1,
            windchill_f: 61.0,
            heatindex_c: 16.1,
            heatindex_f: 61.0,
            dewpoint_c: 10.8,
            dewpoint_f: 51.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.0,
            gust_kph: 19.3,
            uv: 5.0,
          },
          {
            time_epoch: 1717009200,
            time: "2024-05-29 20:00",
            temp_c: 14.7,
            temp_f: 58.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 78,
            cloud: 23,
            feelslike_c: 14.0,
            feelslike_f: 57.1,
            windchill_c: 14.0,
            windchill_f: 57.1,
            heatindex_c: 14.7,
            heatindex_f: 58.4,
            dewpoint_c: 10.8,
            dewpoint_f: 51.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 4.0,
          },
          {
            time_epoch: 1717012800,
            time: "2024-05-29 21:00",
            temp_c: 13.8,
            temp_f: 56.9,
            is_day: 1,
            condition: {
              text: "Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 289,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 83,
            cloud: 79,
            feelslike_c: 13.1,
            feelslike_f: 55.6,
            windchill_c: 13.1,
            windchill_f: 55.6,
            heatindex_c: 13.8,
            heatindex_f: 56.9,
            dewpoint_c: 10.9,
            dewpoint_f: 51.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.8,
            gust_kph: 17.3,
            uv: 3.0,
          },
          {
            time_epoch: 1717016400,
            time: "2024-05-29 22:00",
            temp_c: 13.2,
            temp_f: 55.7,
            is_day: 0,
            condition: {
              text: "Partly Cloudy ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 84,
            cloud: 37,
            feelslike_c: 12.4,
            feelslike_f: 54.4,
            windchill_c: 12.4,
            windchill_f: 54.4,
            heatindex_c: 13.2,
            heatindex_f: 55.7,
            dewpoint_c: 10.6,
            dewpoint_f: 51.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.2,
            gust_kph: 16.4,
            uv: 1.0,
          },
          {
            time_epoch: 1717020000,
            time: "2024-05-29 23:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 300,
            wind_dir: "WNW",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            snow_cm: 0.0,
            humidity: 68,
            cloud: 0,
            feelslike_c: 11.8,
            feelslike_f: 53.2,
            windchill_c: 11.8,
            windchill_f: 53.2,
            heatindex_c: 12.8,
            heatindex_f: 55.0,
            dewpoint_c: 10.3,
            dewpoint_f: 50.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.0,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};
